const scopes = [
  "1st-amendement",
  "2nd-amendement",
  "activism",
  "agriculture",
  "animals",
  "benefits-taxes",
  "census",
  "city-local-government",
  "civic-community",
  "civic-infrastructure",
  "civic-tech",
  "civil-social-rights",
  "covid-19",  
  "culture",
  "democracy-politics",
  "economy-finance",
  "education",
  "emergency-services",
  "employment",
  "elections-voting",
  "energy",
  "environment",
  "food",
  "government",
  "healthcare",
  "homelessness",
  "housing-urban-planning",
  "immigration",
  "international",
  "justice",
  "labor",
  "open-data",
  "poverty",
  "public-safety",
  "social-justice",
  "taxes",
  "sport",
  "transportation",
  "welfare",
];


export default scopes;
